### PR TITLE
avoid warning in scss

### PR DESCRIPTION
**Pull request by osavchenko**
I got [warning](http://content.screencast.com/users/o.savchenko/folders/Jing/media/3807f264-c2ea-4c58-b8e4-0b55f921828d/2015-10-16_1751.png) in my grunt build and propose to avoid such warnings.

### CODE REVIEW

**Comment by shannonmoeller** [comment]
You should be able to correct the warning by changing your import statement to include the `_` prefix:

``` scss
@import '../../vendor/reset-css/_reset';
```

**Comment by osavchenko** [comment]
This is bad solution I think :(

**Comment by shannonmoeller** [comment]
This solution is consistent with the SASS convention of prefixing partial files with an underscore.

http://sass-lang.com/guide#topic-4

**Comment by osavchenko** [comment]
OK, thank you!

**Pull request closed without merging**
